
export const PROFESSIONS = [
  { value: "mechanic", label: "Mexanik" },
  { value: "auto_electrician", label: "Avtoelektrik" },
  { value: "welder", label: "Payvandchi" },
  { value: "hydraulics_specialist", label: "Gidravlik mutaxassisi" },
  { value: "diagnostic_specialist", label: "Diagnostika mutaxassisi" },
  { value: "motor_repairman", label: "Dvigatel ustasi" },
  { value: "transmission_specialist", label: "Transmissiya ustasi" },
  { value: "air_conditioning_specialist", label: "Konditsioner ustasi" },
  { value: "chassis_specialist", label: "Shassi ustasi" },
  { value: "electrician", label: "Elektrik" },
  { value: "engineer", label: "Muhandis" },
  { value: "painter", label: "Bo'yovchi" },
  { value: "body_repair_specialist", label: "Kuzov ustasi" },
  { value: "field_technician", label: "Joyida xizmat ko'rsatuvchi texnik" },
  { value: "parts_specialist", label: "Ehtiyot qismlar mutaxassisi" },
  { value: "service_advisor", label: "Servis maslahatchisi" },
  { value: "loader_operator", label: "Yuk ko'taruvchi operatori" },
  { value: "crane_operator", label: "Kran operatori" },
  { value: "excavator_operator", label: "Ekskavatorchi" },
  { value: "bulldozer_operator", label: "Buldozerchi" },
];

export const WORK_LOCATIONS = [
  { value: "own_place", label: "O'z ustaxonasida" },
  { value: "on_site", label: "Mijoz manzilida" },
  { value: "both", label: "Ham ustaxonada, ham mijoz manzilida" },
];

export const MARKA_FOR_REPAIR = [
  { value: "man", label: "MAN" },
  { value: "talant", label: "TALANT" },
  { value: "caterpillar", label: "CATERPILLAR" },
  { value: "komatsu", label: "KOMATSU" },
  { value: "shantui", label: "SHANTUI" },
  { value: "shehwa_hbxg", label: "SHEHWA / HBXG" },
  { value: "volvo", label: "VOLVO" },
  { value: "hitachi", label: "HITACHI" },
  { value: "jcb", label: "JCB" },
  { value: "hyundai", label: "HYUNDAI" },
  { value: "doosan", label: "DOOSAN" },
  { value: "liebherr", label: "LIEBHERR" },
  { value: "xcmg", label: "XCMG" },
  { value: "case", label: "CASE" },
  { value: "new_holland", label: "NEW HOLLAND" },
  { value: "terex", label: "TEREX" },
  { value: "bobcat", label: "BOBCAT" },
  { value: "yanmar", label: "YANMAR" },
  { value: "sumitomo", label: "SUMITOMO" },
  { value: "kubota", label: "KUBOTA" },
];

export const PROFESSION_BY_MARKA = {
  man: [
    { value: "mechanic", label: "Mexanik" },
    { value: "motor_repairman", label: "Dvigatel ustasi" },
    { value: "transmission_specialist", label: "Transmissiya ustasi" },
    { value: "hydraulics_specialist", label: "Gidravlik mutaxassisi" },
    { value: "auto_electrician", label: "Avtoelektrik" },
  ],
  caterpillar: [
    { value: "mechanic", label: "Mexanik" },
    { value: "hydraulics_specialist", label: "Gidravlik mutaxassisi" },
    { value: "motor_repairman", label: "Dvigatel ustasi" },
    { value: "excavator_operator", label: "Ekskavatorchi" },
    { value: "bulldozer_operator", label: "Buldozerchi" },
  ],
  komatsu: [
    { value: "mechanic", label: "Mexanik" },
    { value: "hydraulics_specialist", label: "Gidravlik mutaxassisi" },
    { value: "motor_repairman", label: "Dvigatel ustasi" },
    { value: "excavator_operator", label: "Ekskavatorchi" },
  ],
  // Add more brands as needed
};

export const PART_MANUFACTURER_BY_PROFESSION = {
  mechanic: [
    { value: "bosch", label: "Bosch" },
    { value: "denso", label: "Denso" },
    { value: "delphi", label: "Delphi" },
    { value: "mahle", label: "Mahle" },
    { value: "mann_filter", label: "MANN-FILTER" },
  ],
  hydraulics_specialist: [
    { value: "bosch", label: "Bosch" },
    { value: "delphi", label: "Delphi" },
    { value: "continental", label: "Continental" },
  ],
  motor_repairman: [
    { value: "mahle", label: "Mahle" },
    { value: "bosch", label: "Bosch" },
    { value: "denso", label: "Denso" },
    { value: "mann_filter", label: "MANN-FILTER" },
  ],
  auto_electrician: [
    { value: "bosch", label: "Bosch" },
    { value: "denso", label: "Denso" },
    { value: "delphi", label: "Delphi" },
    { value: "ngk", label: "NGK" },
  ],
  // Add more professions as needed
};

export const TECH_TYPES = [
  { value: "excavator", label: "Экскаваторы-погрузчики" },
  { value: "water_truck", label: "Водовозы" },
  { value: "overburden_excavator", label: "Вскрышные экскаваторы" },
  { value: "roller", label: "Каток" },
  { value: "construction_cradle", label: "Люльки Cтроительные" },
  { value: "mine_loader", label: "Шахтные погрузчики" },
  { value: "kamaz", label: "камаз" },
  { value: "vacuum_machine", label: "Машина вакуумная" },
  { value: "road_machine", label: "Дорожная машины" },
  { value: "vacuum_cleaner", label: "Вакуумная машина-пылесос" },
  { value: "underground_loader", label: "Подземные погрузчики" },
  { value: "trailer_lift", label: "Прицепные подъемники" },
  { value: "excavator_bulldozer", label: "Экскаваторы-бульдозеры" },
  { value: "spider_crane", label: "Кран-паук" },
  { value: "bulldozer", label: "Бульдозеры" },
  { value: "tracked_excavator", label: "Гусеничные экскаваторы" },
  { value: "front_loader", label: "Фронтальные погрузчики" },
  { value: "mini_loader", label: "Мини-погрузчики" },
  { value: "mini_excavator", label: "Мини-экскаваторы" },
  { value: "mobile_crane", label: "Автокраны" },
  { value: "dump_truck", label: "Самосвалы" },
  { value: "tractor_trailer", label: "Тягачи седельные" },
  { value: "road_roller", label: "Дорожные катки" },
  { value: "crusher", label: "Дробилки" },
  { value: "forklift", label: "Вилочные автопогрузчики" },
  { value: "grader", label: "Грейдеры" },
  { value: "dredger", label: "Земснаряды" },
  { value: "wheel_excavator", label: "Колесные экскаваторы" },
  { value: "pile_driver", label: "Сваебойные установки" },
  { value: "scraper", label: "Скреперы" },
  { value: "trench_excavator", label: "Траншейные экскаваторы" },
  { value: "pile_screw_machine", label: "Установки для завинчивания свай" },
  { value: "amphibious_excavator", label: "Экскаваторы-амфибии" },
  { value: "planning_excavator", label: "Экскаваторы-планировщики" },
  { value: "trailer_house", label: "Бытовки" },
  { value: "tower_crane", label: "Вышки-туры" },
  { value: "generator", label: "Электростанции (Генераторы)" },
  { value: "compact_hydraulic", label: "Компактные гидростанции" },
  { value: "compressor", label: "Компрессоры" },
  { value: "construction_scaffold", label: "Леса строительные" },
  { value: "motor_pump", label: "Мотопомпы" },
  { value: "formwork", label: "Опалубка" },
  { value: "lighting_mast", label: "Осветительные мачты" },
  { value: "welding_unit", label: "Передвижные сварочные агрегаты" },
  { value: "platform", label: "Подмости" },
  { value: "dust_suppression", label: "Системы пылеподавления" },
  { value: "drill_crane", label: "Бурильно-крановые машины" },
  { value: "pile_drill", label: "Буровые станки для устройства свай" },
  { value: "drilling_rig", label: "Буровые установки" },
  { value: "hdd_rig", label: "Установки ГНБ" },
  { value: "dumper", label: "Думперы" },
  { value: "mini_crane", label: "Мини-краны" },
  { value: "mini_tractor", label: "Мини-тракторы" },
  { value: "aerial_lift", label: "Автовышки" },
  { value: "tower_crane_big", label: "Башенные краны" },
  { value: "vacuum_lifter", label: "Вакуумные захваты (подъемники)" },
  { value: "grab_loader", label: "Грейферные погрузчики" },
  { value: "derrick_crane", label: "Деррик-краны" },
  { value: "crawler_crane", label: "Гусеничные краны" },
  { value: "gantry_crane", label: "Козловые краны" },
  { value: "articulated_lift", label: "Коленчатые подъемники" },
  { value: "jib_crane", label: "Консольные краны" },
  { value: "manipulator_crane", label: "Краны-манипуляторы" },
  { value: "mast_lift", label: "Мачтовые подъемники" },
  { value: "bridge_crane", label: "Мостовые краны" },
  { value: "inclined_lift", label: "Наклонные подъемники" },
  { value: "scissor_lift", label: "Ножничные подъемники" },
  { value: "portal_crane", label: "Портальные краны" },
  { value: "bridge_repair", label: "Системы ремонта мостов" },
  { value: "ship_crane", label: "Судовые краны" },
  { value: "telescopic_lift", label: "Телескопические подъемники" },
  { value: "telescopic_handler", label: "Телескопические погрузчики" },
  { value: "pipe_layer", label: "Трубоукладчики" },
  { value: "facade_lift", label: "Фасадные подъемники" },
  { value: "sewage_truck", label: "Ассенизаторские машины" },
  { value: "compost_turner", label: "Ворошители компоста" },
  { value: "waste_shredder", label: "Измельчители отходов" },
  { value: "sludge_sucker", label: "Илососы" },
  { value: "sewer_cleaner", label: "Каналопромывочные машины" },
  { value: "road_sweeper", label: "Комбинированные дорожные машины" },
  { value: "compactor", label: "Компакторы" },
  { value: "garbage_truck", label: "Мусоровозы" },
  { value: "street_sweeper", label: "Подметально-уборочные машины" },
  { value: "washing_truck", label: "Поливомоечные машины" },
  { value: "snow_melter", label: "Снегоплавильные установки" },
  { value: "snow_loader", label: "Снегопогрузчики" },
  { value: "snow_blower", label: "Снегоуборщики" },
  { value: "grass_cutter", label: "Тракторы-газонокосилки" },
  { value: "concrete_mixer", label: "Автобетоносмесители" },
  { value: "asphalt_plant", label: "Асфальтобетонные заводы" },
  { value: "concrete_pump", label: "Автобетононасосы" },
  { value: "concrete_plant", label: "Бетонные заводы" },
  { value: "stationary_pump", label: "Бетононасосы стационарные" },
  { value: "concrete_boom", label: "Бетонораздаточные стрелы" },
  { value: "concrete_mixer_plant", label: "Бетоносмесительные установки" },
  { value: "concrete_paver", label: "Бетоноукладчики" },
  { value: "bitumen_plant", label: "Битумные установки" },
  { value: "deep_vibrator", label: "Вибраторы глубинные" },
  { value: "vibropress", label: "Вибропрессы, виброформовочные машины" },
  { value: "screed_board", label: "Виброрейки" },
  { value: "soil_mixer", label: "Грунтосмесительные установки" },
  { value: "concrete_finisher", label: "Затирочные машины по бетону" },
  { value: "steam_generator", label: "Парогенераторы, термомасляные нагреватели" },
  { value: "mortar_pump", label: "Растворонасосы" },
  { value: "mortar_mixer", label: "Растворосмесители" },
  { value: "cement_silo", label: "Силосы для цемента" },
  { value: "shotcrete_machine", label: "Торкрет-установки" },
  { value: "plaster_station", label: "Штукатурные станции" },
  { value: "tractor_semi", label: "Тракторные полуприцепы" },
  { value: "tractor_trailer_regular", label: "Тракторные прицепы" },
  { value: "tractor", label: "Тракторы" },
  { value: "flatbed_semi", label: "Бортовые полуприцепы" },
  { value: "isothermic_semi", label: "Изотермические полуприцепы" },
  { value: "car_carrier_semi", label: "Полуприцепы-автовозы" },
  { value: "fuel_tanker_semi", label: "Полуприцепы-бензовозы" },
  { value: "bitumen_tanker_semi", label: "Полуприцепы-битумовозы" },
  { value: "gas_tanker_semi", label: "Полуприцепы-газовозы" },
  { value: "grain_semi", label: "Полуприцепы-зерновозы" },
  { value: "container_semi", label: "Полуприцепы-контейнеровозы" },
  { value: "feed_semi", label: "Полуприцепы-кормовозы" },
  { value: "timber_semi", label: "Полуприцепы-лесовозы" },
  { value: "scrap_semi", label: "Полуприцепы-ломовозы" },
  { value: "milk_tanker_semi", label: "Полуприцепы-молоковозы" },
  { value: "panel_semi", label: "Полуприцепы-панелевозы" },
  { value: "refrigerated_semi", label: "Полуприцепы-рефрижераторы" },
  { value: "livestock_semi", label: "Полуприцепы-скотовозы" },
  { value: "fuel_service_semi", label: "Полуприцепы-топливозаправщики" },
  { value: "van_semi", label: "Полуприцепы-фургоны" },
  { value: "cement_tanker_semi", label: "Полуприцепы-цементовозы" },
  { value: "dump_semi", label: "Самосвальные полуприцепы" },
  { value: "curtain_semi", label: "Тентованные полуприцепы" },
  { value: "lowboy", label: "Тралы" },
  { value: "chemical_tanker_semi", label: "Химические полуприцепы-цистерны" },
  { value: "curtain_sliding_semi", label: "Шторные полуприцепы" },
  { value: "flatbed_trailer", label: "Бортовые прицепы" },
  { value: "isothermic_trailer", label: "Изотермические прицепы" },
  { value: "car_carrier_trailer", label: "Прицепы-автовозы" },
  { value: "fuel_tanker_trailer", label: "Прицепы-бензовозы" },
  { value: "grain_trailer", label: "Прицепы-зерновозы" },
  { value: "container_trailer", label: "Прицепы-контейнеровозы" },
  { value: "box_trailer", label: "Прицепы-кунги" },
  { value: "timber_trailer", label: "Прицепы-лесовозы" },
  { value: "scrap_trailer", label: "Прицепы-ломовозы" },
  { value: "milk_tanker_trailer", label: "Прицепы-молоковозы, пищевые" },
  { value: "refrigerated_trailer", label: "Прицепы-рефрижераторы" },
  { value: "livestock_trailer", label: "Прицепы-скотовозы" },
  { value: "heavy_haul_trailer", label: "Прицепы-тяжеловозы" },
  { value: "fuel_service_trailer", label: "Прицепы-топливозаправщики" },
  { value: "pipe_trailer", label: "Прицепы-трубовозы" },
  { value: "van_trailer", label: "Прицепы-фургоны" },
  { value: "dump_trailer", label: "Самосвальные прицепы" },
  { value: "curtain_trailer", label: "Тентованные прицепы" },
  { value: "trailer_chassis", label: "Шасси прицепов" },
  { value: "curtain_sliding_trailer", label: "Шторные прицепы" },
  { value: "mobile_shop", label: "Автолавки" },
  { value: "police_vehicle", label: "Автомобили МВД" },
  { value: "ambulance", label: "Автомобили скорой помощи" },
  { value: "mobile_cabin", label: "Кунги" },
  { value: "mobile_lab", label: "Передвижные лаборатории" },
  { value: "off_road_vehicle", label: "Автомобили-вездеходы, снегоболотоходы" },
  { value: "mobile_workshop", label: "Передвижные мастерские" },
  { value: "fire_truck", label: "Пожарные машины" },
  { value: "mobile_living", label: "Транспортно-бытовые машины" },
  { value: "tow_truck", label: "Эвакуаторы" },
  { value: "feed_truck", label: "Кормовозы" },
  { value: "fuel_truck", label: "Бензовозы" },
  { value: "flatbed_truck", label: "Бортовые кузова" },
  { value: "bitumen_truck", label: "Битумовозы, нефтевозы" },
  { value: "cargo_truck", label: "Бортовые грузовики" },
  { value: "hopper_truck", label: "Бункеровозы" },
  { value: "gas_truck", label: "Газовозы" },
  { value: "van_truck", label: "Грузовые фургоны" },
  { value: "grain_truck", label: "Зерновозы" },
  { value: "isothermic_truck", label: "Изотермические фургоны" },
  { value: "container_truck", label: "Контейнеровозы" },
  { value: "multilift_container", label: "Контейнеры для мультилифта" },
  { value: "van_body", label: "Кузова-фургоны" },
  { value: "timber_truck", label: "Лесовозы" },
  { value: "scrap_truck", label: "Ломовозы" },
  { value: "milk_truck", label: "Молоковозы, пищевые цистерны" },
  { value: "multilift", label: "Мультилифты" },
  { value: "refrigerator", label: "Рефрижераторы" },
  { value: "dump_body", label: "Самосвальные кузова" },
  { value: "tank_container", label: "Танк-контейнеры" },
  { value: "fuel_service_truck", label: "Топливозаправщики" },
  { value: "curtain_truck", label: "Тентованные грузовики" },
  { value: "pipe_truck", label: "Трубовозы" },
  { value: "chemical_tanker", label: "Химические цистерны" },
  { value: "cement_truck", label: "Цементовозы" },
  { value: "chassis", label: "Шасси" },
  { value: "curtain_sliding_truck", label: "Шторные грузовики" },
  { value: "asphalt_distributor", label: "Автогудронаторы" },
  { value: "asphalt_paver", label: "Асфальтоукладчики" },
  { value: "chip_spreader", label: "Битумощебнераспределители" },
  { value: "curb_machine", label: "Бордюроукладчики, уширители обочин" },
  { value: "vibratory_plate", label: "Виброплиты" },
  { value: "vibratory_rammer", label: "Вибротрамбовки" },
  { value: "road_milling", label: "Дорожные фрезы" },
  { value: "crack_sealer", label: "Заливщики швов" },
  { value: "infrared_heater", label: "Инфракрасные нагреватели асфальта" },
  { value: "asphalt_cooker", label: "Кохеры для литого асфальта" },
  { value: "paver_machine", label: "Машины для укладки тротуарной плитки" },
  { value: "pothole_patcher", label: "Машины для ямочного ремонта" },
  { value: "road_marking", label: "Машины дорожной разметки" },
  { value: "material_transfer", label: "Перегружатели" },
  { value: "tack_coat", label: "Распределители вяжущего" },
  { value: "recycler", label: "Ресайклеры, рециклеры" },
  { value: "pavement_dryer", label: "Сушилки дорожного покрытия" },
  { value: "slurry_seal", label: "Укладчики сларри-сил" },
  { value: "joint_cutter", label: "Швонарезчики" },
  { value: "chip_spreader_machine", label: "Щебнераспределители" },
  { value: "mining_support", label: "Вспомогательная горно-шахтная техника" },
  { value: "mining_combine", label: "Горные комбайны" },
  { value: "screen", label: "Грохоты" },
  { value: "dragline", label: "Экскаваторы драглайны" },
  { value: "mining_truck", label: "Карьерные самосвалы" },
  { value: "mining_excavator", label: "Карьерные экскаваторы" },
  { value: "belt_conveyor", label: "Ленточные конвейеры" },
  { value: "magnetic_separator", label: "Магнитные сепараторы" },
  { value: "mill", label: "Мельницы" },
  { value: "stacker", label: "Отвалообразователи" },
  { value: "feeder", label: "Питатели" },
  { value: "load_haul_dump", label: "Погрузочно-доставочные машины" },
  { value: "washing_plant", label: "Промывочное оборудование" },
  { value: "articulated_truck", label: "Сочлененные самосвалы" },
  { value: "flotation_machine", label: "Флотационные машины" },
  { value: "underground_truck", label: "Шахтные самосвалы" },
  { value: "side_loader", label: "Боковые погрузчики" },
  { value: "electric_forklift", label: "Вилочные электропогрузчики" },
  { value: "pallet_jack", label: "Гидравлические тележки" },
  { value: "order_picker", label: "Подборщики заказов" },
  { value: "lift_table", label: "Подъемные столы" },
  { value: "reach_stacker", label: "Ричстакеры" },
  { value: "reach_truck", label: "Ричтраки" },
  { value: "manual_stacker", label: "Ручные штабелеры" },
  { value: "self_propelled_stacker", label: "Самоходные штабелеры" },
  { value: "terminal_tractor", label: "Терминальные тягачи" },
  { value: "narrow_aisle_truck", label: "Узкопроходные штабелеры" },
  { value: "electric_stacker", label: "Электрические штабелеры" },
  { value: "electric_tugger", label: "Электротележки" },
  { value: "electric_tractor", label: "Электротягачи" },
  { value: "feller_buncher", label: "Валочно-пакетирующие машины" },
  { value: "log_loader", label: "Лесопогрузчики" },
  { value: "mulcher", label: "Мульчеры" },
  { value: "chipper", label: "Рубительные машины" },
  { value: "delimber", label: "Сучкорезные машины" },
  { value: "skidder", label: "Трелевочные тракторы" },
  { value: "forwarder", label: "Форвардеры" },
  { value: "harvester", label: "Харвестеры" },
  { value: "cable_layer", label: "Кабелеукладчики" },
  { value: "tensioning_machine", label: "Натяжные машины" },
  { value: "custom_excavator", label: "Нестандартные экскаваторы" },
  { value: "mobile_pump", label: "Передвижные насосные установки" },
  { value: "self_propelled_platform", label: "Самоходные платформы" },
  { value: "demolition_equipment", label: "Техника для демонтажа" },
  { value: "drilling_pump", label: "Буровые насосы" },
  { value: "quick_coupler", label: "Быстросъемы (квик-каплеры)" },
  { value: "vibratory_attachment", label: "Вибротрамбовки навесные" },
  { value: "vibratory_driver", label: "Вибропогружатели" },
  { value: "vibratory_ripper", label: "Виброрыхлители" },
  { value: "forks", label: "Вилы" },
  { value: "hydraulic_breaker", label: "Гидробуры" },
  { value: "magnet", label: "Гидромагниты, электромагниты" },
  { value: "hydraulic_hammer", label: "Гидромолоты" },
  { value: "hydraulic_shears", label: "Гидроножницы" },
  { value: "rake", label: "Грабли навесные" },
  { value: "grapple", label: "Грейферы" },
  { value: "diesel_hammer", label: "Дизель-молоты" },
  { value: "grab", label: "Захваты" },
  { value: "front_loader_attachment", label: "КУНы (погрузчики навесные)" },
  { value: "bucket", label: "Ковши" },
  { value: "stump_grinder", label: "Корчеватели пней" },
  { value: "mower", label: "Косилки навесные" },
  { value: "mulcher_attachment", label: "Мульчеры навесные" },
  { value: "sand_pump", label: "Насосы песковые, шламовые" },
  { value: "snow_blade", label: "Отвалы" },
  { value: "spreader", label: "Пескоразбрасыватели" },
  { value: "spraying_equipment", label: "Поливомоечное оборудование" },
  { value: "ripper", label: "Рыхлители" },
  { value: "snow_plow", label: "Снегоочистители навесные" },
  { value: "tiltrotator", label: "Тилтротаторы" },
  { value: "trencher", label: "Траншеекопатели навесные" },
  { value: "fork_extension", label: "Удлинители вил" },
  { value: "milling_attachment", label: "Фрезы навесные" },
  { value: "harvester_head", label: "Харвестерные головки" },
  { value: "sweeper_brush", label: "Щетки коммунальные" },
  { value: "other_attachment", label: "Прочее навесное" },
  { value: "shuttle_bus", label: "Вахтовые автобусы" },
  { value: "city_bus", label: "Городские автобусы" },
  { value: "intercity_bus", label: "Междугородные автобусы" },
  { value: "suburban_bus", label: "Пригородные автобусы" },
  { value: "tourist_bus", label: "Туристические автобусы" },
  { value: "cargo_passenger_van", label: "Грузопассажирские микроавтобусы" },
  { value: "passenger_van", label: "Пассажирские микроавтобусы" }
];

export const MARKA_BY_TECH_TYPES = {
  excavator: [
    { value: "caterpillar_excavator", label: "Caterpillar" },
    { value: "komatsu_excavator", label: "Komatsu" },
    { value: "hitachi_excavator", label: "Hitachi" },
    { value: "volvo_excavator", label: "Volvo" },
    { value: "jcb_excavator", label: "JCB" },
  ],
  bulldozer: [
    { value: "caterpillar_bulldozer", label: "Caterpillar" },
    { value: "komatsu_bulldozer", label: "Komatsu" },
    { value: "john_deere_bulldozer", label: "John Deere" },
    { value: "case_bulldozer", label: "Case" },
  ],
  crane: [
    { value: "liebherr_crane", label: "Liebherr" },
    { value: "tadano_crane", label: "Tadano" },
    { value: "grove_crane", label: "Grove" },
    { value: "terex_crane", label: "Terex" },
  ],
  loader: [
    { value: "caterpillar_loader", label: "Caterpillar" },
    { value: "volvo_loader", label: "Volvo" },
    { value: "komatsu_loader", label: "Komatsu" },
    { value: "jcb_loader", label: "JCB" },
  ],
};

export const CATEGORY_BY_MARKA = {
  liebherr_crane: [
    { value: "hydraulics", label: "Гидравлика, гидрооборудование" },
    { value: "engines", label: "Двигатели, детали двигателей" },
    { value: "fuel_system", label: "Топливная система" },
    { value: "filters", label: "Фильтры, фильтроэлементы" },
    { value: "chassis", label: "Ходовая часть" },
    { value: "tires_discs", label: "Шины, диски для спецтехники" },
  ],
  caterpillar_bulldozer: [
    { value: "hydraulics", label: "Гидравлика, гидрооборудование" },
    { value: "engines", label: "Двигатели, детали двигателей" },
    { value: "fuel_system", label: "Топливная система" },
    { value: "filters", label: "Фильтры, фильтроэлементы" },
    { value: "chassis", label: "Ходовая часть" },
    { value: "tires_discs", label: "Шины, диски для спецтехники" },
  ],
  caterpillar_loader: [
    { value: "hydraulics", label: "Гидравлика, гидрооборудование" },
    { value: "engines", label: "Двигатели, детали двигателей" },
    { value: "fuel_system", label: "Топливная система" },
  ],
  // Add more categories as needed
};

export const MODEL_BY_MARKA = {
  caterpillar_excavator: [{ value: "cat_320", label: "CAT 320" }],
  komatsu_excavator: [{ value: "pc200", label: "PC200" }],
  hitachi_excavator: [{ value: "zx200", label: "ZX200" }],
  volvo_excavator: [{ value: "ec200", label: "EC200" }],
  jcb_excavator: [{ value: "js200", label: "JS200" }],
  caterpillar_bulldozer: [{ value: "d6", label: "D6" }],
  komatsu_bulldozer: [{ value: "d61", label: "D61" }],
  liebherr_crane: [{ value: "ltm1030", label: "LTM 1030" }],
  tadano_crane: [{ value: "gr250", label: "GR-250N" }],
  caterpillar_loader: [{ value: "950", label: "950 GC" }],
  volvo_loader: [{ value: "l60", label: "L60H" }],
};

export const COUNTRIES = [
  { value: "uzbekistan", label: "O'zbekiston" },
  { value: "russia", label: "Rossiya" },
  { value: "kazakhstan", label: "Qozog'iston" },
  { value: "kyrgyzstan", label: "Qirg'iziston" },
  { value: "tajikistan", label: "Tojikiston" },
  { value: "turkmenistan", label: "Turkmaniston" },
  { value: "azerbaijan", label: "Ozarbayjon" },
  { value: "turkey", label: "Turkiya" },
  { value: "afghanistan", label: "Afg'oniston" },
  { value: "china", label: "Xitoy" },
];

export const CITIES_BY_COUNTRY = {
  uzbekistan: [
    { value: "tashkent", label: "Toshkent" },
    { value: "samarkand", label: "Samarqand" },
    { value: "bukhara", label: "Buxoro" },
    { value: "andijan", label: "Andijon" },
    { value: "fergana", label: "Farg'ona" },
    { value: "namangan", label: "Namangan" },
    { value: "qarshi", label: "Qarshi" },
    { value: "nukus", label: "Nukus" },
    { value: "jizzakh", label: "Jizzax" },
    { value: "urgench", label: "Urganch" },
    { value: "termez", label: "Termiz" },
    { value: "navoi", label: "Navoiy" },
    { value: "gulistan", label: "Guliston" },
    { value: "kokand", label: "Qo'qon" },
  ],
  russia: [
    { value: "moscow", label: "Moskva" },
    { value: "st_petersburg", label: "Sankt-Peterburg" },
    { value: "novosibirsk", label: "Novosibirsk" },
  ],
  kazakhstan: [
    { value: "almaty", label: "Almati" },
    { value: "nur-sultan", label: "Nur-Sultan" },
    { value: "shymkent", label: "Shymkent" },
  ],
  kyrgyzstan: [
    { value: "bishkek", label: "Bishkek" },
    { value: "osh", label: "Osh" },
  ],
  tajikistan: [
    { value: "dushanbe", label: "Dushanbe" },
    { value: "khujand", label: "Xujand" },
  ],
  turkmenistan: [
    { value: "ashgabat", label: "Ashgabat" },
    { value: "turkmenbashi", label: "Turkmenbashi" },
  ],
  azerbaijan: [
    { value: "baku", label: "Boku" },
    { value: "ganja", label: "Ganja" },
  ],
  turkey: [
    { value: "istanbul", label: "Istanbul" },
    { value: "ankara", label: "Ankara" },
    { value: "izmir", label: "Izmir" },
  ],
  afghanistan: [
    { value: "kabul", label: "Kobul" },
    { value: "herat", label: "Herat" },
  ],
  china: [
    { value: "beijing", label: "Pekin" },
    { value: "shanghai", label: "Shanxay" },
  ],
};

export const FUEL_TYPES = [
  { value: "petrol", label: "Benzin" },
  { value: "diesel", label: "Dizel" },
  { value: "gas", label: "Gaz" },
  { value: "electric", label: "Elektr" },
  { value: "petrol-gas", label: "Benzin-Gaz" },
  { value: "hybrid", label: "Gibrid" },
  { value: "not_specified", label: "Belgilanmagan" },
];

// Generate date options
export const DATE_OF_RELEASE = Array.from(
  { length: new Date().getFullYear() - 1970 + 1 },
  (_, i) => {
    const year = new Date().getFullYear() - i;
    return { value: String(year), label: String(year) };
  }
);

// Generate country mapping for categories - har bir category barcha countrylarni qo'llab-quvvatlaydi
export const COUNTRY_BY_CATEGORY = Object.values(CATEGORY_BY_MARKA)
  .flat()
  .reduce((acc, category) => {
    acc[category.value] = COUNTRIES;
    return acc;
  }, {});

// ALL fields have proper initial values (never undefined)
export const INITIAL_FORM_DATA = {
  title: "",
  techType: [],
  description: "",
  price: "",
  isNegotiable: false,
  contact: "",
  phone: "",
  country: "",
  city: "",
  marka: [],
  model: [],
  fuelType: "",
  countriesbymodel: "",
  releaseDate: "",
  mileage: "",
  condition: "",
  cashPayment: "",
  minOrderTime: "",
  haveDriver: "",
  hourlyRate: "",
  partsCategory: "",
  countriesbycategory: "",
  partNumber: "",
  markaForRepair: "",
  profession: [],
  partmanifacturer: [],
  workLocation: "",
  experience: ""
};

// Required fields configuration - YANGI TARTIBDA
export const REQUIRED_FIELDS_CONFIG = {
  // Ehtiyot qismlar sotish
  parts: [
    "title",
    "techType",
    "marka",
    "partsCategory",
    "countriesbycategory",
    "partNumber",
    "condition",
    "description",
    "cashPayment",
    "contact",
    "phone",
    "country",
    "city",
  ],

  // Ta'mir xizmatlari
  repair: [
    "markaForRepair",
    "profession",
    "partmanifacturer",
    "workLocation",
    "description",
    "contact",
    "phone",
    "country",
    "city",
    "experience"
  ],

  // Texnika sotib olish
  purchase: [
    "techType",
    "marka",
    "model",
    "releaseDate",
    "countriesbymodel",
    "fuelType",
    "mileage",
    "condition",
    "description",
    "cashPayment",
    "contact",
    "phone",
    "country",
    "city",
  ],

  // Texnika ijarasi
  rent: [
    "techType",
    "marka",
    "model",
    "releaseDate",
    "minOrderTime",
    "haveDriver",
    "description",
    "contact",
    "phone",
    "country",
    "city",
  ],

  // Haydovchi xizmatlari
  driver: [
    "techType",
    "experience",
    "description",
    "contact",
    "phone",
    "country",
    "city",
  ],
};