export const COUNTRIES = [
  { value: "uz", label: "Узбекистан", flag: "🇺🇿" },
  { value: "af", label: "Афганистан", flag: "🇦🇫" },
  { value: "am", label: "Армения", flag: "🇦🇲" },
  { value: "az", label: "Азербайджан", flag: "🇦🇿" },
  { value: "bh", label: "Бахрейн", flag: "🇧🇭" },
  { value: "bd", label: "Бангладеш", flag: "🇧🇩" },
  { value: "bt", label: "Бутан", flag: "🇧🇹" },
  { value: "bn", label: "Бруней", flag: "🇧🇳" },
  { value: "kh", label: "Камбоджа", flag: "🇰🇭" },
  { value: "cn", label: "Китай", flag: "🇨🇳" },
  { value: "cy", label: "Кипр", flag: "🇨🇾" },
  { value: "ge", label: "Грузия", flag: "🇬🇪" },
  { value: "in", label: "Индия", flag: "🇮🇳" },
  { value: "id", label: "Индонезия", flag: "🇮🇩" },
  { value: "ir", label: "Иран", flag: "🇮🇷" },
  { value: "iq", label: "Ирак", flag: "🇮🇶" },
  { value: "jp", label: "Япония", flag: "🇯🇵" },
  { value: "jo", label: "Иордания", flag: "🇯🇴" },
  { value: "kz", label: "Казахстан", flag: "🇰🇿" },
  { value: "kr", label: "Южная Корея", flag: "🇰🇷" },
  { value: "kw", label: "Кувейт", flag: "🇰🇼" },
  { value: "kg", label: "Кыргызстан", flag: "🇰🇬" },
  { value: "la", label: "Лаос", flag: "🇱🇦" },
  { value: "lb", label: "Ливан", flag: "🇱🇧" },
  { value: "my", label: "Малайзия", flag: "🇲🇾" },
  { value: "mv", label: "Мальдивы", flag: "🇲🇻" },
  { value: "mn", label: "Монголия", flag: "🇲🇳" },
  { value: "mm", label: "Мьянма", flag: "🇲🇲" },
  { value: "np", label: "Непал", flag: "🇳🇵" },
  { value: "om", label: "Оман", flag: "🇴🇲" },
  { value: "pk", label: "Пакистан", flag: "🇵🇰" },
  { value: "ps", label: "Палестина", flag: "🇵🇸" },
  { value: "qa", label: "Катар", flag: "🇶🇦" },
  { value: "ru", label: "Россия", flag: "🇷🇺" },
  { value: "sa", label: "Саудовская Аравия", flag: "🇸🇦" },
  { value: "sg", label: "Сингапур", flag: "🇸🇬" },
  { value: "lk", label: "Шри-Ланка", flag: "🇱🇰" },
  { value: "sy", label: "Сирия", flag: "🇸🇾" },
  { value: "tj", label: "Таджикистан", flag: "🇹🇯" },
  { value: "th", label: "Таиланд", flag: "🇹🇭" },
  { value: "tr", label: "Турция", flag: "🇹🇷" },
  { value: "tm", label: "Туркменистан", flag: "🇹🇲" },
  { value: "ae", label: "Объединённые Арабские Эмираты", flag: "🇦🇪" },
  { value: "vn", label: "Вьетнам", flag: "🇻🇳" },
  { value: "ye", label: "Йемен", flag: "🇾🇪" },
  { value: "hk", label: "Гонконг", flag: "🇭🇰" },
  { value: "mo", label: "Макао", flag: "🇲🇴" },
  { value: "tw", label: "Тайвань", flag: "🇹🇼" },
];
